package de.uni.goettingen.REARClient.Net.SSH;

import java.io.File;
import java.io.FileInputStream;

import com.jcraft.jsch.JSch;
import com.jcraft.jsch.KeyPair;

import de.uni.goettingen.REARClient.PropertiesStore;

public class SSHkey {
	private static final int 	key_size	= 1024;
	private static final int	type		= KeyPair.RSA;
	private static final String	filename	= "id_rsa";
	
	private String	path;
	private File	privKey;
	private File	pubKey;
	
	private KeyPair	kpair;
	
	@SuppressWarnings("deprecation")
	public SSHkey(JSch jsch, PropertiesStore prop) {
		path = prop.getDefaultPath() + "ssh";
		File keyPath = new File(path);
		keyPath.mkdirs();
		privKey = new File(keyPath, filename);
		pubKey  = new File(keyPath, filename + ".pub");
		
		Boolean haveKeys = false;
		
		if(checkFile(privKey)) {
			if(!checkFile(pubKey))
				privKey.delete();
			else
				haveKeys = true;
		}
		
		if(!haveKeys) {
			try {
				kpair = KeyPair.genKeyPair(jsch, type, key_size);
				kpair.setPassphrase(prop.getSSHPassphrase());
				kpair.writePrivateKey(privKey.getAbsolutePath());
				kpair.writePublicKey(pubKey.getAbsolutePath(), "Autogenerated by Exam Screenshot Tool");
				kpair.dispose();
			}
			catch(Exception e) {
				e.printStackTrace();
			}
		}
	}
	
	public File getPrivKey() {
		return privKey;
	}
	
	public File getPubKey() {
		return pubKey;
	}
	
	public String getPubKeyString() {
		String out = "";
		try {
			FileInputStream pubKeyStream = new FileInputStream(pubKey);
			byte[] buff = new byte[1024];
			pubKeyStream.read(buff, 0, 1024);
			out = new String(buff);
			pubKeyStream.close();
		}
		catch(Exception e) { 
			e.printStackTrace(); 
		}
		return out;
	}
	
	private static final Boolean checkFile(File f) {
		if(f.exists() && f.isFile() && f.canRead()) {
			return true;
		}
		return false;
	}
}
